[solution]
name = "moe_fp8_block_scale_ds_routing_topk8_ng8_kg4_e32_h7168_i2048"      # Solution name
definition = "moe_fp8_block_scale_ds_routing_topk8_ng8_kg4_e32_h7168_i2048"  # Full definition name from dataset
author = "vietnamevodich"              # Team/author name

[build]
language = "cuda"               # triton | cuda
entry_point = "kernel.cu::kernel"             # Kernel function name
